### ISSUE TITLE
Global module might be a bad idea

### ISSUE THREAD

**Issue by Jay2k1** [buxxi/znc-mysql#5]
I noticed the most recent version doesn't accept `--type=network` anymore. Looking at the code, it looks like it's a global module now. 

My znc has >10 users, and now all messages of all users are being logged, resulting in duplicate entries in the database when users share a channel. If this is intentional, the (znc) user responsible for the entry should have a column too. I like loading as network or user module better though. I only want to log my own stuff, having my other user's messages in the same DB is kind of privacy invading.

**Comment by buxxi** [comment]
Yeah, you're totally right that it should be a user-module and/or network-module.

For me it has only been a single user (me) using it so no privacy invading there ;)
